export const OWNER_ROUTES = {
  LANDING: '/owner',
  LOGIN: '/owner/login',
  REGISTER: '/owner/register',
  REGISTER_VERIFY: '/owner/register/verify',
  ACCOUNT_PROFILE: '/owner/account',
  ACCOUNT_VERIFICATION: '/owner/verification',
  VEHICLE_ACTIVITY: '/owner/vehicle-activity',
  REVENUE: '/owner/revenue',
  DASHBOARD: '/owner/dashboard',
  VEHICLES: '/owner/vehicles',
  DOCUMENTS: '/owner/documents',
  BOOKINGS: '/owner/bookings',
  MAINTENANCE: '/owner/maintenance',
  PAYMENTS: '/owner/payments',
  WALLET: '/owner/wallet',
  WITHDRAWALS: '/owner/withdrawals',
  RENTAL_PACKAGES: '/owner/rental-packages',
};

import {
  LayoutDashboard,
  Activity,
  Package,
  ClipboardList,
  Wrench,
  Car,
  FileText,
  TrendingUp,
  CreditCard,
  Wallet,
  ArrowDownToLine,
  User,
  ShieldCheck,
} from 'lucide-react';

export const NAV_ITEMS = [
  { label: 'Tổng quan', path: OWNER_ROUTES.DASHBOARD, icon: LayoutDashboard },
  { label: 'Hoạt động xe', path: OWNER_ROUTES.VEHICLE_ACTIVITY, icon: Activity },
  { label: 'Gói thuê xe', path: OWNER_ROUTES.RENTAL_PACKAGES, icon: Package },
  { label: 'Đơn thuê', path: OWNER_ROUTES.BOOKINGS, icon: ClipboardList },
  { label: 'Bảo trì', path: OWNER_ROUTES.MAINTENANCE, icon: Wrench },
  { label: 'Đăng ký xe', path: OWNER_ROUTES.VEHICLES, icon: Car },
  { label: 'Giấy tờ', path: OWNER_ROUTES.DOCUMENTS, icon: FileText },
  { label: 'Doanh thu', path: OWNER_ROUTES.REVENUE, icon: TrendingUp },
  { label: 'Thanh toán', path: OWNER_ROUTES.PAYMENTS, icon: CreditCard },
  { label: 'Ví chủ xe', path: OWNER_ROUTES.WALLET, icon: Wallet },
  { label: 'Rút tiền', path: OWNER_ROUTES.WITHDRAWALS, icon: ArrowDownToLine },
  { label: 'Tài khoản', path: OWNER_ROUTES.ACCOUNT_PROFILE, icon: User },
  { label: 'Xác thực tài khoản', path: OWNER_ROUTES.ACCOUNT_VERIFICATION, icon: ShieldCheck },
];

export const BREADCRUMB_LABELS = {
  owner: 'Chủ xe',
  account: 'Tài khoản',
  verification: 'Xác thực tài khoản',
  'vehicle-activity': 'Hoạt động xe',
  revenue: 'Doanh thu',
  dashboard: 'Tổng quan',
  vehicles: 'Xe của tôi',
  documents: 'Giấy tờ',
  bookings: 'Đơn thuê',
  maintenance: 'Bảo trì',
  payments: 'Thanh toán',
  wallet: 'Ví chủ xe',
  withdrawals: 'Rút tiền',
  'rental-packages': 'Gói thuê xe',
};
