export const OWNER_ROUTES = {
  LANDING: '/owner',
  LOGIN: '/owner/login',
  REGISTER: '/owner/register',
  REGISTER_VERIFY: '/owner/register/verify',
  ACCOUNT_PROFILE: '/owner/account',
  ACCOUNT_VERIFICATION: '/owner/verification',
  VEHICLE_ACTIVITY: '/owner/vehicle-activity',
  REVENUE: '/owner/revenue',
  DASHBOARD: '/owner/dashboard',
  VEHICLES: '/owner/vehicles',
  DOCUMENTS: '/owner/documents',
  BOOKINGS: '/owner/bookings',
  MAINTENANCE: '/owner/maintenance',
  PAYMENTS: '/owner/payments',
  WALLET: '/owner/wallet',
  WITHDRAWALS: '/owner/withdrawals',
  RENTAL_PACKAGES: '/owner/rental-packages',
};

export const NAV_ITEMS = [
  { label: 'Tổng quan', path: OWNER_ROUTES.DASHBOARD },
  { label: 'Tài khoản', path: OWNER_ROUTES.ACCOUNT_PROFILE },
  { label: 'Xác thực tài khoản', path: OWNER_ROUTES.ACCOUNT_VERIFICATION },
  { label: 'Hoạt động xe', path: OWNER_ROUTES.VEHICLE_ACTIVITY },
  { label: 'Xe của tôi', path: OWNER_ROUTES.VEHICLES },
  { label: 'Gói thuê xe', path: OWNER_ROUTES.RENTAL_PACKAGES },
  { label: 'Giấy tờ', path: OWNER_ROUTES.DOCUMENTS },
  { label: 'Đơn thuê', path: OWNER_ROUTES.BOOKINGS },
  { label: 'Bảo trì', path: OWNER_ROUTES.MAINTENANCE },
  { label: 'Doanh thu', path: OWNER_ROUTES.REVENUE },
  { label: 'Thanh toán', path: OWNER_ROUTES.PAYMENTS },
  { label: 'Ví chủ xe', path: OWNER_ROUTES.WALLET },
  { label: 'Rút tiền', path: OWNER_ROUTES.WITHDRAWALS },
];

export const BREADCRUMB_LABELS = {
  owner: 'Chủ xe',
  account: 'Tài khoản',
  verification: 'Xác thực tài khoản',
  'vehicle-activity': 'Hoạt động xe',
  revenue: 'Doanh thu',
  dashboard: 'Tổng quan',
  vehicles: 'Xe của tôi',
  documents: 'Giấy tờ',
  bookings: 'Đơn thuê',
  maintenance: 'Bảo trì',
  payments: 'Thanh toán',
  wallet: 'Ví chủ xe',
  withdrawals: 'Rút tiền',
  'rental-packages': 'Gói thuê xe',
};
