export const queryKeys = {
  profile: ['profile'] as const,
  accountStatus: ['accountStatus'] as const,
  dashboard: ['dashboard'] as const,
  workingOverview: ['workingOverview'] as const,
  activeServiceTypes: ['activeServiceTypes'] as const,
  locationStatus: ['locationStatus'] as const,
  tripCurrent: ['tripCurrent'] as const,
  tripSummary: (tripId: string) => ['tripSummary', tripId] as const,
  historyList: (filters: Record<string, string | undefined>) => ['historyList', filters] as const,
  historyDetail: (tripId: string) => ['historyDetail', tripId] as const,
  walletSummary: ['walletSummary'] as const,
  walletIncomeStats: (period: string, fromDate?: string, toDate?: string) => ['walletIncomeStats', period, fromDate, toDate] as const,
  walletTransactions: (fromDate?: string, toDate?: string) => ['walletTransactions', fromDate, toDate] as const,
  payoutAccount: ['payoutAccount'] as const,
  withdrawalHistory: ['withdrawalHistory'] as const,
  currentTrip: ['currentTrip'] as const,
  history: ['history'] as const,
  wallet: ['wallet'] as const,
  supportTopics: ['supportTopics'] as const,
  supportTickets: ['supportTickets'] as const,
  supportMessages: (ticketId: string) => ['supportMessages', ticketId] as const,
notifications: (group?: string, readState?: string) => ['notifications', group, readState] as const,
  notificationDetail: (notificationId: string) => ['notificationDetail', notificationId] as const,
  notificationsUnreadCount: ['notificationsUnreadCount'] as const,
  driverSchedule: (date: string, viewMode: string) => ['driverSchedule', date, viewMode] as const,
  rentalBookingDetail: (bookingId: string) => ['rentalBookingDetail', bookingId] as const
};
